export const AGENCE_LOADING = 'AGENCE_LOADING';
export const AGENCE_SUCCESS = 'AGENCE_SUCCESS';
export const AGENCE_FAILED = 'AGENCE_FAILED';

export const RESERVATION_LOADING = 'RESERVATION_LOADING';
export const RESERVATION_SUCCESS = 'RESERVATION_SUCCESS';
export const RESERVATION_FAILED = 'RESERVATION_FAILED';